version: '2'

services:
    php_70:
        container_name: php_70
        build: docker
        volumes:
            - ./:/var/www/project
        volumes_from:
            - debian_jessie
        ports:
            - 80:80
        links:
            - db

    db:
        container_name: db
        image: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 3306:3306

    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        links:
          - db
        ports:
          - 8080:80
        environment:
          MYSQL_USERNAME: root
          MYSQL_ROOT_PASSWORD: root